code --install-extension alefragnani.bookmarks
code --install-extension bierner.markdown-preview-github-styles
code --install-extension editorconfig.editorconfig
code --install-extension eg2.vscode-npm-script
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension jvitor83.typings-autoinstaller
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension robertohuertasm.vscode-icons
code --install-extension shardulm94.trailing-spaces
code --install-extension slevesque.vscode-autohotkey
code --install-extension tyriar.sort-lines
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
