code --install-extension bierner.markdown-preview-github-styles
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GrapeCity.gc-excelviewer
code --install-extension jvitor83.typings-autoinstaller
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension richie5um2.vscode-sort-json
code --install-extension ritwickdey.LiveServer
code --install-extension robertohuertasm.vscode-icons
code --install-extension shardulm94.trailing-spaces
code --install-extension shinnn.stylelint
code --install-extension slevesque.vscode-autohotkey
code --install-extension Tyriar.sort-lines
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
