:?*:compatab::compatib
::proccess::process
::literaly::literally
::lit::literally
::def::definitely
::u::you
::ud::you'd
::aswell::as well
::attendent::attendant
::attendents::attendants
::shouldnt::shouldn't
::wouldnt::wouldn't
::couldnt::couldn't
::cant::can't
::should of::should have
::shouldve::should've
::monday::Monday
::tuesday::Tuesday
::wednesday::Wednesday
::thursday::Thursday
::friday::Friday
::saturday::Saturday
::sunday::Sunday
::january::January
::february::February
::april::April
::june::June
::july::July
::august::August
::september::September
::october::October
::november::November
::december::December
::mustve::must've
::muse::μ's
::dont::don't
::whats::what's
::havent::haven't
::ep::episode
::eps::episodes
::prob::probably
::theres::there's
::scroble::scrobble
