::acurate::accurate
::april::April
::aswell::as well
::attendent::attendant
::attendents::attendants
::august::August
::cant::can't
::couldnt::couldn't
::couldntve::couldn't've
::december::December
::def::definitely
::dont::don't
::ep::episode
::eps::episodes
::february::February
::friday::Friday
::havent::haven't
::im::I'm
::itd::it'd
::january::January
::july::July
::june::June
::lit::literally
::literaly::literally
::mightntve::mightn't've
::mightve::might've
::monday::Monday
::muse::μ's
::mustve::must've
::november::November
::october::October
::prob::probably
::proccess::process
::saturday::Saturday
::scroble::scrobble
::september::September
::should of::should have
::shouldnt::shouldn't
::shouldntve::shouldn't've
::shouldve::should've
::sunday::Sunday
::theres::there's
::theyre::they're
::thursday::Thursday
::tuesday::Tuesday
::u::you
::ud::you'd
::wednesday::Wednesday
::whats::what's
::wouldnt::wouldn't
::youre::you're
:?*:compatab::compatib
