#!/usr/bin/env python
from argparse import ArgumentParser
from subprocess import Popen, STDOUT, DEVNULL
from urllib.error import HTTPError
from urllib import request
import json
import os

# CLI definition.
parser = ArgumentParser(description="Clone GitHub user's all repositories.")
parser.add_argument("user", help="GitHub username.")
args = parser.parse_args()

# Clone repositories.
try:
	repos = []
	for repo in json.loads(request.urlopen(f"https://api.github.com/users/{args.user}/repos").read().decode("utf-8")):
		if not os.path.isdir(repo['name']) or len(os.listdir(repo['name'])) == 0:
			repos.append(repo['name'])
		Popen(f"git clone {repo['clone_url']}", stdout=DEVNULL, stderr=STDOUT)
	if len(repos):
		print(f"Cloning {', '.join(repos)}...")
except HTTPError:
	print("Failed to find GitHub user!")
	exit(1)
