#!/usr/bin/env python
from socket import socket, AF_INET, SOCK_DGRAM
from argparse import ArgumentParser
from subprocess import Popen, PIPE
from urllib import request
import platform

# CLI definition.
parser = ArgumentParser(description="Get IP.")
parser.add_argument("-t", "--type", choices=("public", "p", "local", "l"), default="public", metavar="TYPE", help="Specify type.")
parser.add_argument("-c", "--copy", action="store_true", help="Copy to clipboard.")
args = parser.parse_args()

# Fetch IP.
ip = None
if args.type == "public" or args.type == "p":
	ip = request.urlopen("https://checkip.amazonaws.com").read().decode("utf-8")[:-1]
elif args.type == "local" or args.type == "l":
	sock = socket(AF_INET, SOCK_DGRAM)
	sock.connect(('1.1.1.1', 1))
	ip = sock.getsockname()[0]

# Output IP.
print(ip, end="")
if (args.copy):
	process = Popen({ "Windows": "clip", "Darwin": "pbcopy", "Linux": "xclip" }[platform.system()], stdin=PIPE)
	process.stdin.write(bytes(ip, "utf-8"))
	process.stdin.flush()
